server:
  port: 8080
  error:
    include-message: always

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 150MB
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show_sql: false
jwt:
  secret: ${SECRET}
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"