server:
  port: 8080
  error:
    include-message: always

spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/dluznikcht
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
jwt:
  secret: ${SECRET}
logging:
  level:
    org:
      springframework:
        security: DEBUG
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"