name: CI/CD - Backend

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: filip
      DB_PASSWORD: password
    services:
      postgres:
        image: postgres:15.1
        env:
          POSTGRES_USER: filip
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dudios
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build
        run: mvn -ntp -B package -DskipTests
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: filip
      DB_PASSWORD: password
    services:
      postgres:
        image: postgres:15.1
        env:
          POSTGRES_USER: filip
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dudios
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Unit/Integration Tests
        run: mvn -ntp -B test
  deploy:
    needs: [ build, test ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Push docker image
        run: mvn -ntp -B verify jib:build

